name: Publish release

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - run: npm install
      - name: Get version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo $VERSION
      - uses: lannonbr/vsce-action@master
        name: Publish extension
        env:
          VERSION: ${{ steps.vars.outputs.VERSION }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: "publish $VERSION -p $VSCE_TOKEN"
