name: Publish release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - run: npm install
        name: npm install
      - name: Get project version
        id: get_version
        run: |
          echo "echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}"
          echo "$VERSION"
          echo "The github context is:"
          echo "${{ toJson(github) }}"
      - uses: lannonbr/vsce-action@master
        name: Publish extension
        env:
          VERSION: ${{ env.VERSION }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        with:
          args: "publish $VERSION -p $VSCE_TOKEN"
