name: Publish release

on: push

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - run: npm install
      - name: Get version
        id: get_version
        run: |
          echo "::set-env name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"
          echo "$SOURCE_TAG"
          echo "The github context is:"
          echo "${{ toJson(github) }}"
      - name: Testing vars
        run: echo "$SOURCE_TAG"
      # - uses: lannonbr/vsce-action@master
      #   name: Publish extension
      #   env:
      #     VERSION: ${{ env.VERSION }}
      #     VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      #   with:
      #     args: "publish $VERSION -p $VSCE_TOKEN"
